// Import necessary namespaces for system functions, drawing, and Windows Forms.
using System;
using System.Drawing;
using System.Windows.Forms;

// Define the namespace for UI-related classes.
namespace Ergonomy.UI
{
    // This class defines the primary alarm window that appears first.
    // It inherits from Form, making it a standard window.
    public partial class PrimaryAlarmForm : Form
    {
        // This event is used to notify the MainApplicationContext when the form closes.
        // The 'bool' indicates whether the user closed it (true) or it closed automatically (false).
        public event Action<bool> FormClosedCallback;
        // This timer is used to automatically close the window after 7 seconds.
        private System.Windows.Forms.Timer _autoCloseTimer;

        // This is the constructor. It now accepts an AppSettings object.
        public PrimaryAlarmForm(AppSettings settings)
        {
            // This method is automatically generated by the form designer to create the controls (labels, buttons, etc.).
            InitializeComponent();
            // Set the form's starting position to be manually controlled.
            this.StartPosition = FormStartPosition.Manual;
            // Get the working area of the primary screen (the desktop area, excluding the taskbar).
            Rectangle workingArea = Screen.PrimaryScreen.WorkingArea;
            // Set the form's location to the bottom-right corner of the screen.
            this.Location = new Point(workingArea.Right - this.Width, workingArea.Bottom - this.Height);

            // Create a new Timer object for the auto-close functionality.
            _autoCloseTimer = new System.Windows.Forms.Timer();
            // Set the timer's interval from the settings file (converted from seconds to milliseconds).
            _autoCloseTimer.Interval = settings.PrimaryAlarmAutoCloseSeconds * 1000;
            // Define what happens when the timer's interval is reached.
            _autoCloseTimer.Tick += (sender, e) => {
                // When the timer ticks, close the form. The FormClosing event will handle the callback.
                this.Close();
            };
            // Start the auto-close timer.
            _autoCloseTimer.Start();
        }

        // This flag tracks whether the form was closed by the user clicking the 'X' button.
        private bool _isUserClose = false;

        // This method is called just before the form closes. It's the key to the alarm logic.
        protected override void OnFormClosing(FormClosingEventArgs e)
        {
            // --- DIAGNOSTIC LOG ---
            // Log the reason the form is closing. This is crucial for debugging the alarm logic.
            // 'UserClosing' means the user clicked the 'X' button.
            // 'None' (or others) means it was closed programmatically, e.g., by our timer.
            Console.WriteLine($"DIAGNOSTIC: PrimaryAlarmForm closing with reason: {e.CloseReason}");

            // We check the 'CloseReason'. This tells us HOW the close was initiated.
            if (e.CloseReason == CloseReason.UserClosing)
            {
                // Because the user clicked the 'X', we set our flag to true.
                // This is the ONLY time this flag will be set to true.
                _isUserClose = true;
            }
            // Call the base method to allow the form to continue closing.
            base.OnFormClosing(e);
        }

        // This method is called after the form has finished closing.
        protected override void OnFormClosed(FormClosedEventArgs e)
        {
            // Stop the auto-close timer to prevent it from running in the background.
            _autoCloseTimer.Stop();
            // Release the resources used by the timer.
            _autoCloseTimer.Dispose();
            // Invoke the callback event, passing the final value of our flag.
            // If the user clicked 'X', this sends 'true'.
            // If the timer closed the form, this sends 'false'.
            FormClosedCallback?.Invoke(_isUserClose);
            // Call the base method to complete the form closing logic.
            base.OnFormClosed(e);
        }

        // This method contains the code to create and configure all the visual elements on the form.
        // It is typically managed by the Visual Studio designer.
        private void InitializeComponent()
        {
            // Temporarily suspend the layout logic while we add controls.
            this.SuspendLayout();
            //
            // label1: The main text message on the form.
            //
            this.label1 = new System.Windows.Forms.Label();
            this.label1.AutoSize = true; // The label will resize to fit its text.
            this.label1.Font = new System.Drawing.Font("B Nazanin", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.label1.Location = new System.Drawing.Point(12, 9);
            this.label1.Name = "label1";
            this.label1.RightToLeft = System.Windows.Forms.RightToLeft.Yes; // Set text direction for Farsi.
            this.label1.Size = new System.Drawing.Size(250, 42);
            this.label1.TabIndex = 0;
            this.label1.Text = "زمان یک نرمش فرا رسیده است";
            //
            // pictureBox1: The control that displays the animated GIF.
            //
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pictureBox1.Location = new System.Drawing.Point(12, 54);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(250, 150);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage; // The image will stretch to fit the box.
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // Create a list to hold all found image files.
            var imageFiles = new System.Collections.Generic.List<string>();
            // Find all .png files in the assets directory and add them to the list.
            imageFiles.AddRange(System.IO.Directory.GetFiles("assets", "*.png"));
            // Find all .gif files in the assets directory and add them to the list.
            imageFiles.AddRange(System.IO.Directory.GetFiles("assets", "*.gif"));

            // Check if any image files were found to avoid errors.
            if (imageFiles.Count > 0)
            {
                // Create a single Random instance to ensure good randomness.
                var random = new Random();
                // Select a random file path from the list of found files.
                var randomImagePath = imageFiles[random.Next(imageFiles.Count)];
                // Load the randomly selected image into the picture box.
                this.pictureBox1.Image = Image.FromFile(randomImagePath);
            }
            //
            // PrimaryAlarmForm: The main form itself.
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(274, 216); // The size of the window's client area.
            this.Controls.Add(this.pictureBox1); // Add the picture box to the form.
            this.Controls.Add(this.label1); // Add the label to the form.
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow; // A simple window border with a close button.
            this.Name = "PrimaryAlarmForm";
            this.Text = "استراحت"; // The text in the window's title bar.
            // Resume the layout logic now that controls have been added.
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        // Declaration of the label control.
        private System.Windows.Forms.Label label1;
        // Declaration of the picture box control.
        private System.Windows.Forms.PictureBox pictureBox1;
    }
}